import {
  Product,
  RateChange,
  Calculator,
  DataSourceConfig,
  SyncLog,
  ComparisonProfile,
  AdminUser,
  AnalyticsData,
  DashboardMetrics,
} from '@/types/admin';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'FNB Easy Account',
    institution: 'First National Bank',
    productType: 'savings',
    category: 'Transaction Account',
    description: 'Entry-level transaction account with competitive rates',
    applyUrl: 'https://www.fnb.co.za',
    interestRate: 4.25,
    rateType: 'nominal',
    isPromotional: false,
    rateTiers: [
      { minBalance: 0, maxBalance: 10000, rate: 3.5 },
      { minBalance: 10000, maxBalance: 100000, rate: 4.25 },
      { minBalance: 100000, maxBalance: null, rate: 5.0 },
    ],
    minBalance: 0,
    monthlyFee: 99,
    withdrawalFee: 2,
    transactionFee: 1.5,
    setupFee: 0,
    closurePenalty: 0,
    inactivityFee: 25,
    noticePeriodDays: 0,
    minDeposit: 0,
    lockInMonths: 0,
    isTfsaEligible: false,
    isRetirementEligible: false,
    taxStatus: 'Interest taxed at marginal rate',
    residencyRequirement: 'SA Resident',
    dataSource: 'manual_entry',
    sourceUrl: 'https://www.fnb.co.za/accounts',
    lastCheckedDate: '2026-04-01',
    nextRefreshDate: '2026-04-08',
    refreshFrequency: 'weekly',
    status: 'active',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-04-01T14:30:00Z',
    updatedBy: 'admin@everyrands.co.za',
    adminNotes: 'Verify fee structure quarterly',
    publicDisclaimer: 'Rates subject to change without notice',
  },
  {
    id: '2',
    name: 'Capitec Global One',
    institution: 'Capitec Bank',
    productType: 'savings',
    category: 'Savings Account',
    description: 'All-in-one banking solution with market-leading rates',
    applyUrl: 'https://www.capitecbank.co.za',
    interestRate: 7.25,
    rateType: 'nominal',
    isPromotional: false,
    rateTiers: [
      { minBalance: 0, maxBalance: 50000, rate: 6.5 },
      { minBalance: 50000, maxBalance: null, rate: 7.25 },
    ],
    minBalance: 0,
    monthlyFee: 7,
    withdrawalFee: 0,
    transactionFee: 1,
    setupFee: 0,
    closurePenalty: 0,
    inactivityFee: 0,
    noticePeriodDays: 0,
    minDeposit: 0,
    lockInMonths: 0,
    isTfsaEligible: false,
    isRetirementEligible: false,
    taxStatus: 'Interest taxed at marginal rate',
    residencyRequirement: 'SA Resident',
    dataSource: 'website_scrape',
    sourceUrl: 'https://www.capitecbank.co.za/rates',
    lastCheckedDate: '2026-04-05',
    nextRefreshDate: '2026-04-12',
    refreshFrequency: 'weekly',
    status: 'active',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-04-05T09:15:00Z',
    updatedBy: 'editor@everyrands.co.za',
  },
  {
    id: '3',
    name: 'Absa TaxSaver',
    institution: 'Absa Bank',
    productType: 'investment',
    category: 'Tax-Free Savings Account',
    description: 'TFSA with competitive interest and no fees',
    applyUrl: 'https://www.absa.co.za',
    interestRate: 8.5,
    rateType: 'effective',
    isPromotional: false,
    rateTiers: [],
    minBalance: 500,
    monthlyFee: 0,
    withdrawalFee: 0,
    transactionFee: 0,
    setupFee: 0,
    closurePenalty: 0,
    inactivityFee: 0,
    noticePeriodDays: 0,
    minDeposit: 500,
    lockInMonths: 0,
    isTfsaEligible: true,
    isRetirementEligible: false,
    taxStatus: 'Tax-free: no tax on interest, dividends, or capital gains',
    residencyRequirement: 'SA Resident',
    dataSource: 'website_scrape',
    sourceUrl: 'https://www.absa.co.za/tfsa',
    lastCheckedDate: '2026-04-03',
    nextRefreshDate: '2026-04-10',
    refreshFrequency: 'weekly',
    status: 'active',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-04-03T11:00:00Z',
    updatedBy: 'admin@everyrands.co.za',
  },
  {
    id: '4',
    name: 'Standard Bank Notice Deposit',
    institution: 'Standard Bank',
    productType: 'savings',
    category: 'Notice Account',
    description: '32-day notice account with tiered rates',
    applyUrl: 'https://www.standardbank.co.za',
    interestRate: 9.1,
    rateType: 'nominal',
    isPromotional: true,
    promotionalStartDate: '2026-03-01',
    promotionalEndDate: '2026-06-30',
    rateTiers: [
      { minBalance: 10000, maxBalance: 100000, rate: 8.5 },
      { minBalance: 100000, maxBalance: null, rate: 9.1 },
    ],
    minBalance: 10000,
    monthlyFee: 0,
    withdrawalFee: 0,
    transactionFee: 0,
    setupFee: 0,
    closurePenalty: 500,
    inactivityFee: 0,
    noticePeriodDays: 32,
    minDeposit: 10000,
    lockInMonths: 0,
    isTfsaEligible: false,
    isRetirementEligible: false,
    taxStatus: 'Interest taxed at marginal rate',
    residencyRequirement: 'SA Resident',
    dataSource: 'manual_entry',
    sourceUrl: 'https://www.standardbank.co.za/deposits',
    lastCheckedDate: '2026-04-01',
    nextRefreshDate: '2026-04-08',
    refreshFrequency: 'weekly',
    status: 'active',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-04-01T10:00:00Z',
    updatedBy: 'editor@everyrands.co.za',
    publicDisclaimer: 'Promotional rate valid until 30 June 2026',
  },
  {
    id: '5',
    name: 'Nedbank Personal Loan',
    institution: 'Nedbank',
    productType: 'loan',
    category: 'Personal Loan',
    description: 'Flexible personal loan with competitive rates',
    applyUrl: 'https://www.nedbank.co.za',
    interestRate: 21.5,
    rateType: 'effective',
    isPromotional: false,
    rateTiers: [],
    minBalance: 0,
    maxBalance: 300000,
    monthlyFee: 69,
    withdrawalFee: 0,
    transactionFee: 0,
    setupFee: 1207.5,
    closurePenalty: 0,
    inactivityFee: 0,
    noticePeriodDays: 0,
    minDeposit: 0,
    lockInMonths: 6,
    isTfsaEligible: false,
    isRetirementEligible: false,
    taxStatus: 'N/A - Loan product',
    residencyRequirement: 'SA Resident',
    minIncome: 3000,
    creditScoreRequirement: 'Good (650+)',
    dataSource: 'website_scrape',
    sourceUrl: 'https://www.nedbank.co.za/loans',
    lastCheckedDate: '2026-03-28',
    nextRefreshDate: '2026-04-04',
    refreshFrequency: 'weekly',
    status: 'active',
    createdAt: '2026-01-25T10:00:00Z',
    updatedAt: '2026-03-28T16:00:00Z',
    updatedBy: 'admin@everyrands.co.za',
  },
];

export const mockRateChanges: RateChange[] = [
  {
    id: '1',
    productId: '1',
    productName: 'FNB Easy Account',
    institution: 'First National Bank',
    oldRate: 4.0,
    newRate: 4.25,
    changedAt: '2026-04-01T14:30:00Z',
    changedBy: 'admin@everyrands.co.za',
    reason: 'SARB repo rate adjustment',
  },
  {
    id: '2',
    productId: '2',
    productName: 'Capitec Global One',
    institution: 'Capitec Bank',
    oldRate: 7.0,
    newRate: 7.25,
    changedAt: '2026-04-05T09:15:00Z',
    changedBy: 'editor@everyrands.co.za',
    reason: 'Rate update from website scrape',
  },
  {
    id: '3',
    productId: '4',
    productName: 'Standard Bank Notice Deposit',
    institution: 'Standard Bank',
    oldRate: 8.75,
    newRate: 9.1,
    changedAt: '2026-04-01T10:00:00Z',
    changedBy: 'editor@everyrands.co.za',
    reason: 'Promotional rate increase',
  },
];

export const mockCalculators: Calculator[] = [
  {
    id: '1',
    name: 'PAYE / Income Tax Calculator',
    description: 'Calculate your monthly PAYE tax and net salary using SARS 2026 brackets',
    status: 'enabled',
    lastUpdated: '2026-03-01',
    testCaseCount: 12,
    formula: '// 2026 SARS tax brackets\n// R0 - R237,100: 18%\n// R237,101 - R370,500: 26%\n// etc.',
    inputs: [
      { id: '1', name: 'grossSalary', label: 'Gross Monthly Salary', type: 'currency', required: true, helpText: 'Your total monthly income before deductions', min: 0 },
      { id: '2', name: 'age', label: 'Age', type: 'number', required: true, min: 18, max: 100 },
      { id: '3', name: 'medicalAidMembers', label: 'Medical Aid Members', type: 'number', required: false, defaultValue: 0, min: 0 },
    ],
    outputs: [
      { id: '1', name: 'taxableIncome', label: 'Taxable Income', format: 'currency', showBreakdown: true },
      { id: '2', name: 'incomeTax', label: 'Income Tax', format: 'currency', showBreakdown: true },
      { id: '3', name: 'netSalary', label: 'Net Salary', format: 'currency', showBreakdown: false },
    ],
  },
  {
    id: '2',
    name: 'Home Loan / Bond Calculator',
    description: 'Calculate monthly bond repayments and total interest',
    status: 'enabled',
    lastUpdated: '2026-02-15',
    testCaseCount: 8,
    formula: '// Monthly payment = P * [r(1+r)^n] / [(1+r)^n - 1]',
    inputs: [
      { id: '1', name: 'propertyPrice', label: 'Property Price', type: 'currency', required: true, min: 100000 },
      { id: '2', name: 'deposit', label: 'Deposit Amount', type: 'currency', required: true, min: 0 },
      { id: '3', name: 'interestRate', label: 'Interest Rate (%)', type: 'percentage', required: true, min: 0, max: 30, defaultValue: 10.25 },
      { id: '4', name: 'termYears', label: 'Loan Term (Years)', type: 'number', required: true, min: 1, max: 30, defaultValue: 20 },
    ],
    outputs: [
      { id: '1', name: 'monthlyPayment', label: 'Monthly Repayment', format: 'currency', showBreakdown: false },
      { id: '2', name: 'totalInterest', label: 'Total Interest Paid', format: 'currency', showBreakdown: true },
      { id: '3', name: 'totalCost', label: 'Total Cost', format: 'currency', showBreakdown: false },
    ],
  },
  {
    id: '3',
    name: 'TFSA Contribution Tracker',
    description: 'Track TFSA contributions against annual (R46,000) and lifetime (R500,000) limits',
    status: 'enabled',
    lastUpdated: '2026-03-01',
    testCaseCount: 6,
    formula: '// Annual limit: R46,000 (from 1 March 2026)\n// Lifetime limit: R500,000',
    inputs: [
      { id: '1', name: 'currentContributions', label: 'Contributions This Tax Year', type: 'currency', required: true, min: 0 },
      { id: '2', name: 'previousContributions', label: 'All Previous Contributions', type: 'currency', required: true, min: 0 },
    ],
    outputs: [
      { id: '1', name: 'remainingAnnual', label: 'Remaining Annual Allowance', format: 'currency', showBreakdown: false },
      { id: '2', name: 'remainingLifetime', label: 'Remaining Lifetime Allowance', format: 'currency', showBreakdown: false },
      { id: '3', name: 'penaltyRisk', label: 'Penalty Risk', format: 'number', showBreakdown: true },
    ],
  },
  {
    id: '4',
    name: 'Savings Growth Calculator',
    description: 'Calculate compound interest growth on savings',
    status: 'enabled',
    lastUpdated: '2026-02-01',
    testCaseCount: 10,
    formula: '// A = P(1 + r/n)^(nt) + PMT * [(1 + r/n)^(nt) - 1] / (r/n)',
    inputs: [
      { id: '1', name: 'initialDeposit', label: 'Initial Deposit', type: 'currency', required: true, min: 0 },
      { id: '2', name: 'monthlyContribution', label: 'Monthly Contribution', type: 'currency', required: false, defaultValue: 0, min: 0 },
      { id: '3', name: 'interestRate', label: 'Annual Interest Rate (%)', type: 'percentage', required: true, min: 0, max: 30 },
      { id: '4', name: 'termYears', label: 'Investment Term (Years)', type: 'number', required: true, min: 1, max: 50 },
    ],
    outputs: [
      { id: '1', name: 'futureValue', label: 'Future Value', format: 'currency', showBreakdown: false },
      { id: '2', name: 'totalContributions', label: 'Total Contributions', format: 'currency', showBreakdown: false },
      { id: '3', name: 'totalInterest', label: 'Interest Earned', format: 'currency', showBreakdown: false },
    ],
  },
  {
    id: '5',
    name: 'Loan Repayment Calculator',
    description: 'Calculate monthly loan repayments and amortization schedule',
    status: 'enabled',
    lastUpdated: '2026-02-15',
    testCaseCount: 9,
    formula: '// Standard amortization formula',
    inputs: [
      { id: '1', name: 'loanAmount', label: 'Loan Amount', type: 'currency', required: true, min: 1000 },
      { id: '2', name: 'interestRate', label: 'Annual Interest Rate (%)', type: 'percentage', required: true, min: 0, max: 50 },
      { id: '3', name: 'termMonths', label: 'Loan Term (Months)', type: 'number', required: true, min: 1, max: 360 },
      { id: '4', name: 'initiationFee', label: 'Initiation Fee', type: 'currency', required: false, defaultValue: 0 },
    ],
    outputs: [
      { id: '1', name: 'monthlyPayment', label: 'Monthly Payment', format: 'currency', showBreakdown: false },
      { id: '2', name: 'totalRepayment', label: 'Total Repayment', format: 'currency', showBreakdown: false },
      { id: '3', name: 'totalInterest', label: 'Total Interest', format: 'currency', showBreakdown: false },
    ],
  },
  {
    id: '6',
    name: 'Debt Snowball/Avalanche Calculator',
    description: 'Optimal debt repayment strategy calculator',
    status: 'enabled',
    lastUpdated: '2026-01-15',
    testCaseCount: 7,
    formula: '// Snowball: smallest balance first\n// Avalanche: highest rate first',
    inputs: [
      { id: '1', name: 'extraPayment', label: 'Extra Monthly Payment', type: 'currency', required: true, min: 0 },
      { id: '2', name: 'strategy', label: 'Strategy', type: 'dropdown', required: true, options: ['Snowball', 'Avalanche'] },
    ],
    outputs: [
      { id: '1', name: 'debtFreeDate', label: 'Debt-Free Date', format: 'date', showBreakdown: false },
      { id: '2', name: 'totalInterestSaved', label: 'Interest Saved', format: 'currency', showBreakdown: false },
    ],
  },
  {
    id: '7',
    name: 'Car Finance Calculator',
    description: 'Calculate car finance repayments including balloon payments',
    status: 'enabled',
    lastUpdated: '2026-02-01',
    testCaseCount: 8,
    formula: '// Includes balloon payment option',
    inputs: [
      { id: '1', name: 'vehiclePrice', label: 'Vehicle Price', type: 'currency', required: true, min: 10000 },
      { id: '2', name: 'deposit', label: 'Deposit', type: 'currency', required: false, defaultValue: 0, min: 0 },
      { id: '3', name: 'interestRate', label: 'Interest Rate (%)', type: 'percentage', required: true, defaultValue: 11.25 },
      { id: '4', name: 'termMonths', label: 'Term (Months)', type: 'number', required: true, defaultValue: 72 },
      { id: '5', name: 'balloonPercent', label: 'Balloon Payment (%)', type: 'percentage', required: false, defaultValue: 0, max: 40 },
    ],
    outputs: [
      { id: '1', name: 'monthlyPayment', label: 'Monthly Payment', format: 'currency', showBreakdown: false },
      { id: '2', name: 'totalCost', label: 'Total Cost', format: 'currency', showBreakdown: false },
    ],
  },
  {
    id: '8',
    name: 'Net-to-Gross Salary Calculator',
    description: 'Reverse calculate gross salary from net (take-home) salary',
    status: 'enabled',
    lastUpdated: '2026-03-01',
    testCaseCount: 5,
    formula: '// Iterative calculation to find gross from net',
    inputs: [
      { id: '1', name: 'netSalary', label: 'Take-Home Salary', type: 'currency', required: true, min: 0 },
      { id: '2', name: 'age', label: 'Age', type: 'number', required: true, min: 18 },
    ],
    outputs: [
      { id: '1', name: 'grossSalary', label: 'Gross Salary', format: 'currency', showBreakdown: true },
      { id: '2', name: 'taxAmount', label: 'Tax Amount', format: 'currency', showBreakdown: false },
    ],
  },
];

export const mockDataSources: DataSourceConfig[] = [
  {
    id: '1',
    name: 'SARB Monetary Policy API',
    type: 'SARB_API',
    endpoint: 'https://api.sarb.co.za/monetary-policy',
    refreshSchedule: '0 6 * * *',
    lastSyncAt: '2026-04-11T06:00:00Z',
    lastSyncStatus: 'success',
    nextScheduledSync: '2026-04-12T06:00:00Z',
    isActive: true,
  },
  {
    id: '2',
    name: 'SARS Tax Brackets',
    type: 'SARS',
    endpoint: 'https://www.sars.gov.za/individuals/tax-and-retirement/',
    refreshSchedule: '0 0 1 3 *',
    lastSyncAt: '2026-03-01T00:00:00Z',
    lastSyncStatus: 'success',
    nextScheduledSync: '2027-03-01T00:00:00Z',
    isActive: true,
  },
  {
    id: '3',
    name: 'Bank Website Scraper',
    type: 'website_scrape',
    refreshSchedule: '0 8 * * 1',
    lastSyncAt: '2026-04-07T08:00:00Z',
    lastSyncStatus: 'partial',
    nextScheduledSync: '2026-04-14T08:00:00Z',
    isActive: true,
  },
];

export const mockSyncLogs: SyncLog[] = [
  {
    id: '1',
    sourceId: '1',
    sourceName: 'SARB Monetary Policy API',
    startedAt: '2026-04-11T06:00:00Z',
    completedAt: '2026-04-11T06:00:45Z',
    status: 'success',
    recordsProcessed: 12,
    recordsUpdated: 3,
    errors: [],
    duration: 45,
  },
  {
    id: '2',
    sourceId: '3',
    sourceName: 'Bank Website Scraper',
    startedAt: '2026-04-07T08:00:00Z',
    completedAt: '2026-04-07T08:04:20Z',
    status: 'partial',
    recordsProcessed: 45,
    recordsUpdated: 38,
    errors: [
      'Failed to scrape Absa fixed deposit page: 503 Service Unavailable',
      'Rate parsing failed for Nedbank Money Market',
    ],
    duration: 260,
  },
];

export const mockComparisonProfiles: ComparisonProfile[] = [
  {
    id: '1',
    name: 'Emergency Savings',
    description: 'Best for emergency funds - prioritizes quick access and low fees',
    weights: {
      interestRate: 30,
      fees: 20,
      accessibility: 40,
      minBalance: 10,
    },
    isDefault: true,
  },
  {
    id: '2',
    name: 'TFSA Maximizer',
    description: 'Best for maximising tax-free savings',
    weights: {
      interestRate: 50,
      fees: 10,
      accessibility: 0,
      minBalance: 0,
      tfsaEligibility: 40,
    },
    mustBeTfsa: true,
    isDefault: true,
  },
  {
    id: '3',
    name: 'Large Balance',
    description: 'Best for large deposits (R100k+)',
    weights: {
      interestRate: 40,
      fees: 30,
      accessibility: 0,
      minBalance: 10,
      tierMatching: 20,
    },
    isDefault: true,
  },
  {
    id: '4',
    name: 'No-Fee Banking',
    description: 'Best for fee-conscious customers',
    weights: {
      interestRate: 20,
      fees: 70,
      accessibility: 10,
      minBalance: 0,
    },
    isDefault: true,
  },
  {
    id: '5',
    name: 'Short-Term Parking',
    description: 'Best for temporarily parking cash',
    weights: {
      interestRate: 20,
      fees: 20,
      accessibility: 50,
      minBalance: 0,
      noticePeriod: 10,
    },
    isDefault: true,
  },
];

export const mockAdminUsers: AdminUser[] = [
  {
    id: '1',
    name: 'Reece Josephs',
    email: 'admin@everyrands.co.za',
    role: 'Admin',
    status: 'active',
    lastLogin: '2026-04-11T19:00:00Z',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'editor@everyrands.co.za',
    role: 'Editor',
    status: 'active',
    lastLogin: '2026-04-10T14:30:00Z',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Mark Peters',
    email: 'viewer@everyrands.co.za',
    role: 'Viewer',
    status: 'inactive',
    lastLogin: '2026-03-01T09:00:00Z',
    createdAt: '2026-02-01T00:00:00Z',
  },
];

export const mockAnalytics: AnalyticsData = {
  calculatorUsage: [
    { name: 'PAYE Tax', uses: 4521 },
    { name: 'Bond Calculator', uses: 3892 },
    { name: 'Savings Growth', uses: 2756 },
    { name: 'TFSA Tracker', uses: 2341 },
    { name: 'Loan Repayment', uses: 1987 },
    { name: 'Car Finance', uses: 1456 },
    { name: 'Debt Snowball', uses: 987 },
    { name: 'Net-to-Gross', uses: 654 },
  ],
  productViews: [
    { name: 'Capitec Global One', views: 8921, institution: 'Capitec Bank' },
    { name: 'FNB Easy Account', views: 6543, institution: 'First National Bank' },
    { name: 'Absa TaxSaver', views: 5432, institution: 'Absa Bank' },
    { name: 'Standard Bank Notice', views: 4123, institution: 'Standard Bank' },
    { name: 'Nedbank Personal Loan', views: 3456, institution: 'Nedbank' },
  ],
  trafficOverTime: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.UTC(2026, 2, 13) + i * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    visitors: 200 + ((i * 37 + 13) % 500),
    pageViews: 600 + ((i * 113 + 47) % 1500),
  })),
  deviceBreakdown: [
    { device: 'Mobile', percentage: 62 },
    { device: 'Desktop', percentage: 31 },
    { device: 'Tablet', percentage: 7 },
  ],
  profileUsage: [
    { name: 'Emergency Savings', uses: 3421 },
    { name: 'TFSA Maximizer', uses: 2876 },
    { name: 'No-Fee Banking', uses: 2345 },
    { name: 'Large Balance', uses: 1234 },
    { name: 'Short-Term Parking', uses: 987 },
  ],
};

export const mockDashboardMetrics: DashboardMetrics = {
  totalProducts: mockProducts.length,
  productsByType: [
    { type: 'Savings', count: 3 },
    { type: 'Loans', count: 1 },
    { type: 'Investment', count: 1 },
  ],
  lastSyncAt: '2026-04-11T06:00:00Z',
  dataFreshness: 'fresh',
  staleProducts: 1,
  activeUsers: 3,
  recentActivity: [
    {
      id: '1',
      type: 'rate_change',
      description: 'FNB Easy Account rate updated from 4.0% to 4.25%',
      user: 'admin@everyrands.co.za',
      timestamp: '2026-04-11T14:30:00Z',
    },
    {
      id: '2',
      type: 'sync',
      description: 'SARB API sync completed: 3 products updated',
      timestamp: '2026-04-11T06:00:45Z',
    },
    {
      id: '3',
      type: 'product_update',
      description: 'Capitec Global One fees verified',
      user: 'editor@everyrands.co.za',
      timestamp: '2026-04-10T09:15:00Z',
    },
    {
      id: '4',
      type: 'alert',
      description: 'Standard Bank Notice Deposit rate change >1%',
      timestamp: '2026-04-01T10:00:00Z',
    },
  ],
  dataQualityIssues: [
    { type: 'missing_field', count: 2, description: 'Products missing source URL' },
    { type: 'validation_error', count: 1, description: 'Rate tier overlap detected' },
  ],
};
