import type {
  Product,
  Calculator,
  DataSource,
  ComparisonProfile,
  RateHistory,
  DashboardMetrics,
  SystemSettings,
} from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Standard Bank PureSave',
    institution: 'Standard Bank',
    type: 'savings',
    category: 'savings_account',
    description: 'A flexible savings account with tiered interest rates.',
    status: 'active',
    interestRate: 4.5,
    rateType: 'nominal',
    isPromotional: false,
    rateTiers: [
      { minBalance: 0, maxBalance: 9999, rate: 3.5 },
      { minBalance: 10000, maxBalance: 49999, rate: 4.5 },
      { minBalance: 50000, maxBalance: null, rate: 5.0 },
    ],
    compoundingFrequency: 'monthly',
    monthlyFee: 0,
    withdrawalFee: 0,
    adminFee: 0,
    openingFee: 0,
    closurePenalty: 0,
    otherFees: [],
    minDeposit: 0,
    maxBalance: undefined,
    accessType: '24/7',
    isTfsaEligible: false,
    taxTreatment: 'regular_income',
    sourceUrl: 'https://www.standardbank.co.za/savings',
    lastCheckedDate: '2026-04-01',
    lastCheckedBy: 'admin',
    verificationStatus: 'verified',
    nextReviewDate: '2026-05-01',
    updateFrequency: 'monthly',
    notes: 'Interest paid monthly.',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-04-01T10:30:00Z',
  },
  {
    id: 'p2',
    name: 'Nedbank JustInvest',
    institution: 'Nedbank',
    type: 'savings',
    category: 'fixed_deposit',
    description: '12-month fixed deposit with competitive rates.',
    status: 'active',
    interestRate: 9.25,
    rateType: 'effective',
    isPromotional: false,
    rateTiers: [],
    compoundingFrequency: 'annually',
    monthlyFee: 0,
    withdrawalFee: 0,
    adminFee: 0,
    openingFee: 0,
    closurePenalty: 1000,
    otherFees: [],
    minDeposit: 1000,
    minTerm: 12,
    accessType: 'notice_period',
    noticePeriodDays: 32,
    isTfsaEligible: false,
    taxTreatment: 'regular_income',
    sourceUrl: 'https://www.nedbank.co.za/fixed-deposit',
    lastCheckedDate: '2026-03-28',
    lastCheckedBy: 'editor1',
    verificationStatus: 'verified',
    nextReviewDate: '2026-04-28',
    updateFrequency: 'monthly',
    notes: 'Early withdrawal penalty applies.',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-03-28T14:00:00Z',
  },
  {
    id: 'p3',
    name: 'FNB Tax-Free Account',
    institution: 'FNB',
    type: 'savings',
    category: 'tfsa',
    description: 'Tax-free savings account with annual limit of R46,000.',
    status: 'active',
    interestRate: 6.8,
    rateType: 'effective',
    isPromotional: false,
    rateTiers: [],
    compoundingFrequency: 'monthly',
    monthlyFee: 0,
    withdrawalFee: 0,
    adminFee: 0,
    openingFee: 0,
    closurePenalty: 0,
    otherFees: [],
    minDeposit: 100,
    accessType: '24/7',
    isTfsaEligible: true,
    taxTreatment: 'tax_free',
    sourceUrl: 'https://www.fnb.co.za/tfsa',
    lastCheckedDate: '2026-04-05',
    lastCheckedBy: 'admin',
    verificationStatus: 'verified',
    nextReviewDate: '2026-05-05',
    updateFrequency: 'monthly',
    notes: 'Annual limit R46,000. Lifetime limit R500,000.',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-04-05T11:00:00Z',
  },
  {
    id: 'p4',
    name: 'Absa Personal Loan',
    institution: 'Absa',
    type: 'loan',
    category: 'personal_loan',
    description: 'Unsecured personal loan up to R350,000.',
    status: 'active',
    interestRate: 24.5,
    rateType: 'nominal',
    isPromotional: false,
    rateTiers: [],
    compoundingFrequency: 'monthly',
    monthlyFee: 69,
    withdrawalFee: 0,
    adminFee: 0,
    openingFee: 1207.5,
    closurePenalty: 0,
    otherFees: [],
    minDeposit: 0,
    minIncome: 3000,
    maxBalance: 350000,
    minTerm: 12,
    accessType: 'business_hours',
    isTfsaEligible: false,
    taxTreatment: 'regular_income',
    sourceUrl: 'https://www.absa.co.za/personal-loan',
    lastCheckedDate: '2026-04-02',
    lastCheckedBy: 'editor1',
    verificationStatus: 'verified',
    nextReviewDate: '2026-05-02',
    updateFrequency: 'monthly',
    notes: 'Rate varies by risk profile.',
    createdAt: '2026-01-25T08:00:00Z',
    updatedAt: '2026-04-02T09:00:00Z',
  },
  {
    id: 'p5',
    name: 'TymeBank GoalSave',
    institution: 'TymeBank',
    type: 'savings',
    category: 'savings_account',
    description: 'Goal-based digital savings account with bonus rates.',
    status: 'active',
    interestRate: 11.0,
    rateType: 'effective',
    isPromotional: true,
    promotionEndDate: '2026-06-30',
    rateTiers: [],
    compoundingFrequency: 'daily',
    monthlyFee: 0,
    withdrawalFee: 0,
    adminFee: 0,
    openingFee: 0,
    closurePenalty: 0,
    otherFees: [],
    minDeposit: 0,
    accessType: '24/7',
    isTfsaEligible: false,
    taxTreatment: 'regular_income',
    sourceUrl: 'https://www.tymebank.co.za/goalsave',
    lastCheckedDate: '2026-04-08',
    lastCheckedBy: 'admin',
    verificationStatus: 'verified',
    nextReviewDate: '2026-04-22',
    updateFrequency: 'weekly',
    notes: 'Promotional rate – review before expiry.',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-04-08T12:00:00Z',
  },
  {
    id: 'p6',
    name: 'Standard Bank Home Loan',
    institution: 'Standard Bank',
    type: 'loan',
    category: 'home_loan',
    description: 'Competitive variable rate home loan (prime-linked).',
    status: 'active',
    interestRate: 10.25,
    rateType: 'nominal',
    isPromotional: false,
    rateTiers: [],
    compoundingFrequency: 'monthly',
    monthlyFee: 69,
    withdrawalFee: 0,
    adminFee: 0,
    openingFee: 6000,
    closurePenalty: 0,
    otherFees: [],
    minDeposit: 0,
    minIncome: 15000,
    minTerm: 120,
    accessType: 'business_hours',
    isTfsaEligible: false,
    taxTreatment: 'regular_income',
    sourceUrl: 'https://www.standardbank.co.za/home-loan',
    lastCheckedDate: '2026-04-03',
    lastCheckedBy: 'admin',
    verificationStatus: 'verified',
    nextReviewDate: '2026-05-03',
    updateFrequency: 'monthly',
    notes: 'Rate at prime. Subject to credit approval.',
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-04-03T10:00:00Z',
  },
  {
    id: 'p7',
    name: 'Capitec Global One',
    institution: 'Capitec',
    type: 'savings',
    category: 'transaction_account',
    description: 'All-in-one transaction and savings account.',
    status: 'active',
    interestRate: 2.5,
    rateType: 'nominal',
    isPromotional: false,
    rateTiers: [],
    compoundingFrequency: 'monthly',
    monthlyFee: 7,
    withdrawalFee: 1,
    adminFee: 0,
    openingFee: 0,
    closurePenalty: 0,
    otherFees: [],
    minDeposit: 0,
    accessType: '24/7',
    isTfsaEligible: false,
    taxTreatment: 'regular_income',
    sourceUrl: 'https://www.capitecbank.co.za/global-one',
    lastCheckedDate: '2026-03-15',
    lastCheckedBy: 'editor1',
    verificationStatus: 'unverified',
    nextReviewDate: '2026-04-15',
    updateFrequency: 'monthly',
    notes: 'R7/month fee includes multiple benefits.',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-03-15T14:00:00Z',
  },
];

export const MOCK_RATE_HISTORY: RateHistory[] = [
  {
    id: 'rh1',
    productId: 'p1',
    productName: 'Standard Bank PureSave',
    institution: 'Standard Bank',
    oldRate: 4.0,
    newRate: 4.5,
    effectiveDate: '2026-03-01',
    changedBy: 'admin',
    reason: 'market_change',
    notes: 'SARB rate adjustment.',
    createdAt: '2026-03-01T09:00:00Z',
  },
  {
    id: 'rh2',
    productId: 'p3',
    productName: 'FNB Tax-Free Account',
    institution: 'FNB',
    oldRate: 6.5,
    newRate: 6.8,
    effectiveDate: '2026-02-15',
    changedBy: 'editor1',
    reason: 'market_change',
    notes: 'Rate revised by FNB.',
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'rh3',
    productId: 'p5',
    productName: 'TymeBank GoalSave',
    institution: 'TymeBank',
    oldRate: 9.0,
    newRate: 11.0,
    effectiveDate: '2026-01-15',
    changedBy: 'admin',
    reason: 'promo',
    notes: 'Promotional rate introduced.',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'rh4',
    productId: 'p4',
    productName: 'Absa Personal Loan',
    institution: 'Absa',
    oldRate: 25.0,
    newRate: 24.5,
    effectiveDate: '2026-03-20',
    changedBy: 'editor1',
    reason: 'correction',
    notes: 'Corrected rate after verification.',
    createdAt: '2026-03-20T11:00:00Z',
  },
];

export const MOCK_CALCULATORS: Calculator[] = [
  {
    id: 'c1',
    name: 'PAYE / Income Tax',
    slug: 'paye',
    description: 'Calculate South African income tax (PAYE) based on 2026 SARS tax tables.',
    category: 'Tax',
    status: 'active',
    featured: true,
    inputs: [
      { id: 'i1', name: 'grossIncome', label: 'Annual Gross Income (R)', type: 'currency', required: true, min: 0, helpText: 'Your total annual income before deductions.', order: 1 },
      { id: 'i2', name: 'age', label: 'Age', type: 'number', required: true, min: 18, max: 100, helpText: 'Your age affects the tax rebate applied.', order: 2 },
      { id: 'i3', name: 'retirementContrib', label: 'Retirement Contributions (R)', type: 'currency', required: false, min: 0, helpText: 'Annual retirement fund contributions (tax deductible).', order: 3 },
    ],
    outputs: [
      { id: 'o1', name: 'annualTax', label: 'Annual Tax Payable', format: 'currency', description: 'Total PAYE for the tax year.', order: 1 },
      { id: 'o2', name: 'monthlyTax', label: 'Monthly Tax Deduction', format: 'currency', description: 'Monthly PAYE deduction from salary.', order: 2 },
      { id: 'o3', name: 'effectiveRate', label: 'Effective Tax Rate', format: 'percentage', description: 'Your effective (average) tax rate.', order: 3 },
      { id: 'o4', name: 'netIncome', label: 'Annual Net Income', format: 'currency', description: 'Take-home pay after tax.', order: 4 },
    ],
    formula: `// 2026 SARS Tax Tables
const brackets = [
  { min: 0, max: 237100, rate: 0.18, base: 0 },
  { min: 237101, max: 370500, rate: 0.26, base: 42678 },
  { min: 370501, max: 512800, rate: 0.31, base: 77362 },
  { min: 512801, max: 673000, rate: 0.36, base: 121475 },
  { min: 673001, max: 857900, rate: 0.39, base: 179147 },
  { min: 857901, max: 1817000, rate: 0.41, base: 251258 },
  { min: 1817001, max: Infinity, rate: 0.45, base: 644489 },
];
const rebates = { primary: 17235, secondary: 9444, tertiary: 3145 };`,
    taxYear: 2026,
    dataSources: ['SARS 2026 Tax Tables'],
    testCases: [
      { id: 't1', name: 'Basic salary R30k/month', inputs: { grossIncome: 360000, age: 35, retirementContrib: 0 }, expectedOutputs: { annualTax: 66339, effectiveRate: '18.43' } },
    ],
    usageToday: 142,
    usageWeek: 980,
    usageMonth: 4230,
    lastModified: '2026-03-01T10:00:00Z',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'c2',
    name: 'Loan Repayment',
    slug: 'loan-repayment',
    description: 'Calculate monthly repayments and total cost for any loan.',
    category: 'Loans',
    status: 'active',
    featured: true,
    inputs: [
      { id: 'i1', name: 'principal', label: 'Loan Amount (R)', type: 'currency', required: true, min: 1000, helpText: 'The amount you want to borrow.', order: 1 },
      { id: 'i2', name: 'rate', label: 'Annual Interest Rate (%)', type: 'percentage', required: true, min: 0, max: 100, helpText: 'The nominal annual interest rate.', order: 2 },
      { id: 'i3', name: 'term', label: 'Loan Term (months)', type: 'number', required: true, min: 1, max: 360, helpText: 'The number of monthly repayments.', order: 3 },
    ],
    outputs: [
      { id: 'o1', name: 'monthlyRepayment', label: 'Monthly Repayment', format: 'currency', description: 'Fixed monthly payment amount.', order: 1 },
      { id: 'o2', name: 'totalRepayment', label: 'Total Amount Repaid', format: 'currency', description: 'Total paid over the full term.', order: 2 },
      { id: 'o3', name: 'totalInterest', label: 'Total Interest Paid', format: 'currency', description: 'Total cost of the loan.', order: 3 },
    ],
    formula: 'M = P * [r(1+r)^n] / [(1+r)^n – 1]',
    taxYear: 2026,
    dataSources: ['SARB Prime Rate'],
    testCases: [],
    usageToday: 89,
    usageWeek: 620,
    usageMonth: 2800,
    lastModified: '2026-02-15T10:00:00Z',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'c3',
    name: 'TFSA Tracker',
    slug: 'tfsa-tracker',
    description: 'Track TFSA contributions and remaining annual/lifetime allowances.',
    category: 'Savings',
    status: 'active',
    featured: true,
    inputs: [
      { id: 'i1', name: 'currentContrib', label: 'Contributions This Tax Year (R)', type: 'currency', required: true, min: 0, helpText: 'Total TFSA contributions from 1 March to date.', order: 1 },
      { id: 'i2', name: 'lifetimeContrib', label: 'Total Lifetime Contributions (R)', type: 'currency', required: true, min: 0, helpText: 'All TFSA contributions since inception.', order: 2 },
    ],
    outputs: [
      { id: 'o1', name: 'remainingAnnual', label: 'Remaining Annual Allowance', format: 'currency', description: 'Still available to contribute this tax year.', order: 1 },
      { id: 'o2', name: 'remainingLifetime', label: 'Remaining Lifetime Allowance', format: 'currency', description: 'Still available over your lifetime.', order: 2 },
      { id: 'o3', name: 'overContribution', label: 'Over-Contribution Amount', format: 'currency', description: 'Amount exceeding allowed limits (penalised by SARS).', order: 3 },
    ],
    formula: 'remainingAnnual = 46000 - currentContrib; remainingLifetime = 500000 - lifetimeContrib;',
    taxYear: 2026,
    dataSources: ['SARS TFSA Limits 2026'],
    testCases: [
      { id: 't1', name: 'Full year contribution', inputs: { currentContrib: 46000, lifetimeContrib: 184000 }, expectedOutputs: { remainingAnnual: 0, remainingLifetime: 316000, overContribution: 0 } },
    ],
    usageToday: 56,
    usageWeek: 390,
    usageMonth: 1640,
    lastModified: '2026-03-01T09:00:00Z',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'c4',
    name: 'Savings Growth',
    slug: 'savings-growth',
    description: 'Project savings growth with compound interest over time.',
    category: 'Savings',
    status: 'active',
    featured: false,
    inputs: [
      { id: 'i1', name: 'initialDeposit', label: 'Initial Deposit (R)', type: 'currency', required: true, min: 0, helpText: 'Starting amount.', order: 1 },
      { id: 'i2', name: 'monthlyContrib', label: 'Monthly Contribution (R)', type: 'currency', required: false, min: 0, helpText: 'Regular monthly deposit.', order: 2 },
      { id: 'i3', name: 'rate', label: 'Annual Interest Rate (%)', type: 'percentage', required: true, min: 0, max: 50, helpText: 'Nominal annual rate.', order: 3 },
      { id: 'i4', name: 'years', label: 'Savings Period (years)', type: 'number', required: true, min: 1, max: 50, helpText: 'Number of years to save.', order: 4 },
    ],
    outputs: [
      { id: 'o1', name: 'futureValue', label: 'Future Value', format: 'currency', description: 'Total value at end of period.', order: 1 },
      { id: 'o2', name: 'totalContributions', label: 'Total Contributions', format: 'currency', description: 'Sum of all deposits.', order: 2 },
      { id: 'o3', name: 'interestEarned', label: 'Interest Earned', format: 'currency', description: 'Total interest accrued.', order: 3 },
    ],
    formula: 'FV = P*(1+r/n)^(n*t) + PMT * ((1+r/n)^(n*t) - 1) / (r/n)',
    taxYear: 2026,
    dataSources: [],
    testCases: [],
    usageToday: 34,
    usageWeek: 248,
    usageMonth: 1020,
    lastModified: '2026-01-15T10:00:00Z',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'c5',
    name: 'Bond / Home Loan',
    slug: 'bond-calculator',
    description: 'Calculate home loan repayments, affordability, and total cost.',
    category: 'Loans',
    status: 'active',
    featured: true,
    inputs: [
      { id: 'i1', name: 'propertyValue', label: 'Property Value (R)', type: 'currency', required: true, min: 0, helpText: 'Purchase price of the property.', order: 1 },
      { id: 'i2', name: 'deposit', label: 'Deposit (R)', type: 'currency', required: false, min: 0, helpText: 'Upfront deposit amount.', order: 2 },
      { id: 'i3', name: 'rate', label: 'Interest Rate (%)', type: 'percentage', required: true, min: 0, max: 30, helpText: 'Current prime-linked rate (default 10.25%).', order: 3 },
      { id: 'i4', name: 'term', label: 'Bond Term (years)', type: 'number', required: true, min: 5, max: 30, helpText: 'Loan term in years.', order: 4 },
    ],
    outputs: [
      { id: 'o1', name: 'monthlyRepayment', label: 'Monthly Repayment', format: 'currency', description: '', order: 1 },
      { id: 'o2', name: 'totalCost', label: 'Total Cost of Bond', format: 'currency', description: '', order: 2 },
      { id: 'o3', name: 'totalInterest', label: 'Total Interest', format: 'currency', description: '', order: 3 },
    ],
    formula: 'Standard amortisation with prime-linked rate.',
    taxYear: 2026,
    dataSources: ['SARB Prime Rate (10.25%)'],
    testCases: [],
    usageToday: 112,
    usageWeek: 780,
    usageMonth: 3400,
    lastModified: '2026-03-15T10:00:00Z',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'c6',
    name: 'Debt Snowball / Avalanche',
    slug: 'debt-snowball',
    description: 'Plan your debt payoff strategy using snowball or avalanche method.',
    category: 'Debt',
    status: 'beta',
    featured: false,
    inputs: [
      { id: 'i1', name: 'extraPayment', label: 'Extra Monthly Payment (R)', type: 'currency', required: false, min: 0, helpText: 'Additional amount beyond minimums.', order: 1 },
      { id: 'i2', name: 'method', label: 'Strategy', type: 'select', required: true, options: ['Snowball (lowest balance first)', 'Avalanche (highest rate first)'], helpText: 'Choose your payoff strategy.', order: 2 },
    ],
    outputs: [
      { id: 'o1', name: 'payoffMonths', label: 'Total Months to Debt-Free', format: 'number', description: '', order: 1 },
      { id: 'o2', name: 'totalInterestSaved', label: 'Interest Saved', format: 'currency', description: '', order: 2 },
    ],
    formula: 'Dynamic payoff order based on strategy.',
    taxYear: 2026,
    dataSources: [],
    testCases: [],
    usageToday: 22,
    usageWeek: 145,
    usageMonth: 590,
    lastModified: '2026-02-01T10:00:00Z',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'c7',
    name: 'Net-to-Gross Salary',
    slug: 'net-to-gross',
    description: 'Convert a desired net salary to the required gross salary.',
    category: 'Tax',
    status: 'active',
    featured: false,
    inputs: [
      { id: 'i1', name: 'targetNet', label: 'Desired Monthly Net (R)', type: 'currency', required: true, min: 0, helpText: 'Take-home amount you want.', order: 1 },
      { id: 'i2', name: 'age', label: 'Age', type: 'number', required: true, min: 18, max: 100, helpText: '', order: 2 },
    ],
    outputs: [
      { id: 'o1', name: 'requiredGross', label: 'Required Gross Monthly', format: 'currency', description: '', order: 1 },
      { id: 'o2', name: 'monthlyTax', label: 'Monthly Tax', format: 'currency', description: '', order: 2 },
    ],
    formula: 'Iterative approximation using SARS PAYE tables.',
    taxYear: 2026,
    dataSources: ['SARS 2026 Tax Tables'],
    testCases: [],
    usageToday: 48,
    usageWeek: 330,
    usageMonth: 1380,
    lastModified: '2026-03-01T10:00:00Z',
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 'c8',
    name: 'Retirement Contribution',
    slug: 'retirement-contribution',
    description: 'Calculate optimal retirement contributions and projected retirement income.',
    category: 'Retirement',
    status: 'active',
    featured: false,
    inputs: [
      { id: 'i1', name: 'currentAge', label: 'Current Age', type: 'number', required: true, min: 18, max: 65, helpText: '', order: 1 },
      { id: 'i2', name: 'retirementAge', label: 'Retirement Age', type: 'number', required: true, min: 55, max: 75, helpText: '', order: 2 },
      { id: 'i3', name: 'currentSavings', label: 'Current Savings (R)', type: 'currency', required: false, min: 0, helpText: '', order: 3 },
      { id: 'i4', name: 'monthlyContrib', label: 'Monthly Contribution (R)', type: 'currency', required: true, min: 0, helpText: '', order: 4 },
      { id: 'i5', name: 'expectedReturn', label: 'Expected Annual Return (%)', type: 'percentage', required: true, min: 0, max: 20, helpText: 'Conservative: 8%, Balanced: 10–12%.', order: 5 },
    ],
    outputs: [
      { id: 'o1', name: 'projectedSavings', label: 'Projected Savings at Retirement', format: 'currency', description: '', order: 1 },
      { id: 'o2', name: 'monthlyIncome', label: 'Estimated Monthly Retirement Income', format: 'currency', description: 'Assuming 4% annual drawdown.', order: 2 },
    ],
    formula: 'Compound growth with monthly contributions.',
    taxYear: 2026,
    dataSources: [],
    testCases: [],
    usageToday: 31,
    usageWeek: 210,
    usageMonth: 880,
    lastModified: '2026-01-20T10:00:00Z',
    createdAt: '2026-01-01T08:00:00Z',
  },
];

export const MOCK_DATA_SOURCES: DataSource[] = [
  {
    id: 's1',
    name: 'SARB Policy Rate API',
    type: 'api',
    endpoint: 'https://www.resbank.co.za/api/rates',
    refreshFrequency: 'daily',
    lastSync: {
      id: 'sl1',
      sourceId: 's1',
      timestamp: '2026-04-11T06:00:00Z',
      duration: 4200,
      recordsProcessed: 1,
      recordsAdded: 0,
      recordsUpdated: 1,
      recordsDeleted: 0,
      errors: [],
      status: 'success',
    },
    nextScheduledSync: '2026-04-12T06:00:00Z',
    syncHistory: [],
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's2',
    name: 'SARS Tax Bracket Data',
    type: 'manual',
    endpoint: 'https://www.sars.gov.za/tax-rates',
    refreshFrequency: 'manual',
    lastSync: {
      id: 'sl2',
      sourceId: 's2',
      timestamp: '2026-03-01T09:00:00Z',
      duration: 1200,
      recordsProcessed: 7,
      recordsAdded: 7,
      recordsUpdated: 0,
      recordsDeleted: 7,
      errors: [],
      status: 'success',
    },
    syncHistory: [],
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
  },
  {
    id: 's3',
    name: 'FNB Product Feed',
    type: 'scraping',
    endpoint: 'https://www.fnb.co.za/rates',
    refreshFrequency: 'weekly',
    lastSync: {
      id: 'sl3',
      sourceId: 's3',
      timestamp: '2026-04-08T07:30:00Z',
      duration: 12400,
      recordsProcessed: 12,
      recordsAdded: 0,
      recordsUpdated: 3,
      recordsDeleted: 0,
      errors: ['Timeout on product page 4 – retried successfully'],
      status: 'warning',
    },
    nextScheduledSync: '2026-04-15T07:30:00Z',
    syncHistory: [],
    isActive: true,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 's4',
    name: 'Absa Rate Feed',
    type: 'api',
    endpoint: 'https://api.absa.co.za/rates',
    refreshFrequency: 'weekly',
    lastSync: {
      id: 'sl4',
      sourceId: 's4',
      timestamp: '2026-04-05T08:00:00Z',
      duration: 0,
      recordsProcessed: 0,
      recordsAdded: 0,
      recordsUpdated: 0,
      recordsDeleted: 0,
      errors: ['401 Unauthorized – API key expired'],
      status: 'failed',
    },
    nextScheduledSync: '2026-04-12T08:00:00Z',
    syncHistory: [],
    isActive: false,
    createdAt: '2026-01-15T08:00:00Z',
  },
];

export const MOCK_PROFILES: ComparisonProfile[] = [
  {
    id: 'pr1',
    name: 'Emergency Savings',
    description: 'Best for building an accessible emergency fund. Prioritises liquidity and no fees.',
    weights: { interestRate: 20, fees: 30, accessFlexibility: 30, minBalanceRequirement: 10, tfsaEligibility: 0, digitalEaseOfUse: 5, userProfileMatch: 5 },
    productTypes: ['savings'],
    categories: ['savings_account', 'money_market'],
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'pr2',
    name: 'TFSA Optimisation',
    description: 'Maximise tax-free returns. Prioritises TFSA eligibility and high effective yield.',
    weights: { interestRate: 35, fees: 15, accessFlexibility: 10, minBalanceRequirement: 5, tfsaEligibility: 30, digitalEaseOfUse: 3, userProfileMatch: 2 },
    productTypes: ['savings'],
    categories: ['tfsa', 'savings_account'],
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'pr3',
    name: 'Large Balances',
    description: 'For balances above R100,000. Prioritises highest effective yield.',
    weights: { interestRate: 50, fees: 10, accessFlexibility: 10, minBalanceRequirement: 10, tfsaEligibility: 10, digitalEaseOfUse: 5, userProfileMatch: 5 },
    productTypes: ['savings'],
    categories: ['fixed_deposit', 'notice_deposit', 'money_market'],
    minBalance: 100000,
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'pr4',
    name: 'No-Fee Banking',
    description: 'Best for those wanting minimal banking costs.',
    weights: { interestRate: 10, fees: 50, accessFlexibility: 20, minBalanceRequirement: 10, tfsaEligibility: 0, digitalEaseOfUse: 5, userProfileMatch: 5 },
    productTypes: ['savings'],
    categories: ['transaction_account', 'savings_account'],
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'pr5',
    name: 'Short-term Parking',
    description: 'Best for temporarily parking cash with easy access.',
    weights: { interestRate: 30, fees: 20, accessFlexibility: 35, minBalanceRequirement: 5, tfsaEligibility: 0, digitalEaseOfUse: 5, userProfileMatch: 5 },
    productTypes: ['savings'],
    categories: ['savings_account', 'money_market', 'notice_deposit'],
    isActive: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
];

export const MOCK_DASHBOARD: DashboardMetrics = {
  totalProducts: 7,
  productsByType: { savings: 5, loan: 2, investment: 0 },
  dataFreshnessPercent: 71,
  lastSyncTimestamps: {
    'SARB Policy Rate': '2026-04-11T06:00:00Z',
    'SARS Tax Brackets': '2026-03-01T09:00:00Z',
    'FNB Feed': '2026-04-08T07:30:00Z',
    'Absa Feed': '2026-04-05T08:00:00Z',
  },
  syncFailures: 1,
  popularCalculators: [
    { name: 'PAYE / Income Tax', usage: 4230 },
    { name: 'Bond / Home Loan', usage: 3400 },
    { name: 'Loan Repayment', usage: 2800 },
    { name: 'TFSA Tracker', usage: 1640 },
    { name: 'Net-to-Gross', usage: 1380 },
  ],
  mostComparedProducts: [
    { name: 'FNB Tax-Free Account', comparisons: 312 },
    { name: 'TymeBank GoalSave', comparisons: 287 },
    { name: 'Standard Bank PureSave', comparisons: 241 },
  ],
  productsAddedThisMonth: 2,
  ratesUpdatedThisMonth: 4,
  errorsFixed: 2,
  systemHealth: 'healthy',
};

export const MOCK_SETTINGS: SystemSettings = {
  siteTitle: 'EveryRandSA',
  siteDescription: 'South Africa\'s financial comparison and calculator platform.',
  contactEmail: 'admin@everyrand.co.za',
  alertRecipients: ['admin@everyrand.co.za', 'data@everyrand.co.za'],
  defaultRefreshFrequency: 'weekly',
  dataRetentionDays: 365,
  rateChangeSensitivity: 10,
  autoArchiveOutdated: false,
  autoArchiveThresholdDays: 90,
};
